apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
spec:
  selector:
    matchLabels:
      app: healthcare
  replicas: 2
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare-app
          image: shoaibpathan/healthcare:1.0
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  type: LoadBalancer

